name: Push Docker containers to Docker Hub

on:
  workflow_dispatch: # For manual triggering
  release:
    types:
      - published

jobs:
  build:
    name: Build Docker containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ["face-extractor", "speaker-identifier", "voice-extractor", "audio-transcriber", "sentiment-extractor"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build component from release tag
        uses: docker/build-push-action@v3
        if: github.ref != 'main'
        with:
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
            branch=${{ github.ref }}
          context: ./docker/${{ matrix.component }}
          push: true
          no-cache: true
          tags: mexca/${{ matrix.component }}:${{ github.ref }}
      - name: Build component from main as 'latest' tag
        uses: docker/build-push-action@v3
        if: github.ref == 'main'
        with:
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
            branch=${{ github.ref }}
          context: ./docker/${{ matrix.component }}
          push: true
          no-cache: true
          tags: mexca/${{ matrix.component }}:latest
