name: Docker containers

on:
  workflow_dispatch: # For manual triggering
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Build Docker containers
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     component: ["face-extractor", "speaker-identifier", "voice-extractor", "audio-transcriber", "sentiment-extractor"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build FaceExtractor
        uses: docker/build-push-action@v3
        with:
          build-args: branch=github.ref_name
          context: ./docker/face-extractor
          load: true
          push: false
          tags: mexca/face-extractor
      - name: Build SpeakerIdentifier
        uses: docker/build-push-action@v3
        with:
          build-args: HF_TOKEN=${{secrets.HF_TOKEN }},branch=github.ref_name
          context: ./docker/speaker-identifier
          load: true
          push: false
          tags: mexca/speaker-identifier
      - name: Build VoiceExtractor
        uses: docker/build-push-action@v3
        with:
          build-args: branch=github.ref_name
          context: ./docker/voice-extractor
          load: true
          push: false
          tags: mexca/voice-extractor
      - name: Build AudioTranscriber
        uses: docker/build-push-action@v3
        with:
          build-args: branch=github.ref_name
          context: ./docker/audio-transcriber
          load: true
          push: false
          tags: mexca/audio-transcriber
      - name: Build SentimentExtractor
        uses: docker/build-push-action@v3
        with:
          build-args: branch=github.ref_name
          context: ./docker/sentiment-extractor
          load: true
          push: false
          tags: mexca/sentiment-extractor
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: 'pip'
          cache-dependency-path: setup.cfg
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install .[dev]
      - name: Run container tests
        env:
          HF_TOKEN: ${{secrets.HF_TOKEN }}
        run: pytest -vv tests/test_container.py
